### ISSUE TITLE
Concurrent access detected

### ISSUE THREAD

**Issue by wilsonjr** [TutteInstitute/evoc#1]
Hello @lmcinnes, thanks for another library!

I am just pointing out what seems to be a problem for arm-based processors (I am on M2).

After executing the blobs example of the readme page, I get:

```
Numba workqueue threading layer is terminating: Concurrent access has been detected.

 - The workqueue threading layer is not threadsafe and may not be accessed concurrently by multiple threads. Concurrent access typically occurs through a nested parallel region launch or by calling Numba parallel=True functions from multiple Python threads.
 - Try using the TBB threading layer as an alternative, as it is, itself, threadsafe. Docs: https://numba.readthedocs.io/en/stable/user/threading-layer.html
```

when execution reaches [float_nndescent.py#L305](https://github.com/TutteInstitute/evoc/blob/89e37c366e946432ffcdd20b38b632ce07454ffd/evoc/float_nndescent.py#L305).

**Comment by lmcinnes** [comment]
Yes, you need to have tbb installed otherwise it does not work well on Mac. With tbb enabled it should run (it worked for me).

**Comment by enjalot** [comment]
How do you have tbb installed? I can't get my python virtual env to recognize tbb after `brew install tbb`
Apparently tbb and tbb4py are not available in pip?

ChatGPT keeps recommending conda which is the only thing I haven't tried yet.

**Comment by lmcinnes** [comment]
I use conda, and that worked for me. I thought it was available on pip: https://pypi.org/project/tbb/ ? Perhaps that is not installing though.

**Comment by enjalot** [comment]
Yeah, I tried for an hour to use brew + virtualenv with no luck.
I will try with conda to give the library a shot (very excited to try it!), but it will be hard to add as a dependency if I can't install it via pip :(

**Comment by lmcinnes** [comment]
I definitely understand that. I'll have to see if there are some decent work-around solutions available.

**Comment by lmcinnes** [comment]
So it looks like openmp threading will do the job; it is definitely slower, but functional. Of course you still at least need openmp installed and working.

**Comment by enjalot** [comment]
it works for me now! thank you ❤️
