### ISSUE TITLE
Possible to set a random seed? 

### ISSUE THREAD

**Issue by zilch42** [TutteInstitute/evoc#10]
Just wondering if it would be possible to allow setting a random seed so that results could be reproducible between runs with the same data and input parameters?

**Comment by lmcinnes** [comment]
Some of the speed comes from parallelism that has race conditions. That means that even with fixed seeds it is not reproducible. I figured it was better not to have a seed that would imply some sort of reproducibility when it simply isn't available.

**Comment by zilch42** [comment]
No worries thanks!
