### ISSUE TITLE
Still experiencing NumPy AttributeError (np.bool)

### ISSUE THREAD

**Issue by sean-doody** [TutteInstitute/evoc#14]
Hey there,

I saw a [previous commit](https://github.com/TutteInstitute/evoc/commit/a37e2548d56434aa4285c6519c7e6e0ba97ad00b) that seemed to correct for a deprecated NumPy alias, but I am still getting an `AttributeError` for the use of `np.bool` (I'm running NumPy 1.26.4):

```
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

Simulated usage:

```python
embeddings = np.random.uniform(-1, 1, (100, 768))
clusterer = evoc.EVoC()
cluster_labels = clusterer.fit_predict(embeddings)
```

Thanks!

**Update:** Changing `np.bool` to `np.bool_` works for NumPy < 2.0, but `np.bool` has returned as the primary alias in [NumPy >= 2.0](https://numpy.org/doc/stable/release/2.0.0-notes.html).

**Comment by lmcinnes** [comment]
I'm afraid I may have to leave things as is to be numpy 2.0 compatible going forward.
