### ISSUE TITLE
Numba warning on initialization

### ISSUE THREAD

**Issue by zilch42** [TutteInstitute/evoc#9]
I get the following warning when initializing an EVoC class object. 

```
import evoc

clusterer = evoc.EVoC()
```
```
[c:\Users\Me\AppData\Local\miniconda3\envs\my-env\lib\site-packages\evoc\float_nndescent.py:287](file:///C:/Users/Me/AppData/Local/miniconda3/envs/my-env/lib/site-packages/evoc/float_nndescent.py:287): NumbaTypeSafetyWarning: unsafe cast from uint64 to int64. Precision may be lost.
  points = point_indices[i]
```

Is this anything to be concerned about? 
Numba version 0.60.0

**Comment by lmcinnes** [comment]
No, I don't think it is anything to worry about. I've tried tracing the
warning and the lines/details it gives are no help at all. I think it
maybin fact be a spurious warning.
